### ISSUE TITLE
New designs

### ISSUE THREAD

**Issue by digitalghost-dev** [Mqxx/GitHub-Markdown#1]
Hey, opening an issue for new badges. Some suggestions:

- Checkmark but with label says "success" and/or "working"
- Maybe a `danger` badge with [this icon](https://primer.style/octicons/no-entry-16) to [this one](https://primer.style/octicons/zap-16)?
- A `tip` badge with [this icon](https://primer.style/octicons/light-bulb-16)?

I'm pulling inspiration from [Obsidian callouts](https://help.obsidian.md/How+to/Use+callouts)

**Comment by Mqxx** [comment]
> * Checkmark but with label says "success" and/or "working"

Okay which icon should I use for the checkmark?

**Comment by Mqxx** [comment]
> * Checkmark but with label says "success" and/or "working"

Okay I will add both of them. But, there is already a checkmark with success.

**Comment by Mqxx** [comment]
I have added the "Danger" badge with [this icon](https://primer.style/octicons/stop-16)

**Comment by Mqxx** [comment]
I'm following the [GitHub design guidelines](https://primer.style/design/components/icon)

**Comment by ghost** [comment]
> > * Checkmark but with label says "success" and/or "working"
> 
> Okay I will add both of them. But, there is already a checkmark with success.

Yes, but just wanted different labels that is more meaningful.
Cool, thanks for the link on the design link. How do you feel about a `tip` badge?

**Comment by Mqxx** [comment]
What color sould I use for the "Tip" badge?

**Comment by ghost** [comment]
Black or gray?

**Comment by Mqxx** [comment]
Thats exacly what I have thought of 😄

**Comment by Mqxx** [comment]
> * A `tip` badge with [this icon](https://primer.style/octicons/light-bulb-16)?

Added!

**Comment by ghost** [comment]
Danger one looks good! The gray might be too light? I opened up the `svg` file and it's a bit hard to see.

**Comment by Mqxx** [comment]
Yea I know but in a dark markdown file I think it looks good.

**Comment by Mqxx** [comment]
> * Checkmark but with label says "success" and/or "working"

I'm not quite sure about the "alternate success badges" yet, because like I said I'm sticking to the GitHub styling guidelines

**Comment by ghost** [comment]
Should there be a light/dark version for tip? I use light mode a lot lol

**Comment by Mqxx** [comment]
> Should there be a light/dark version for tip? I use light mode a lot lol

Oh yea I can also create a light and dark color theme of each badge

**Comment by Mqxx** [comment]
Added! https://github.com/Mqxx/GitHub-Markdown/blob/main/blockquotes/badge/light-theme/tip.svg

**Comment by ghost** [comment]
Awesome. They look great.

**Comment by Mqxx** [comment]
Anything else?

**Comment by ghost** [comment]
Do you like the idea of an "example" badge?

**Comment by Mqxx** [comment]
Yea maybe. What Icon should I use?

**Comment by ghost** [comment]
Maybe [this one](https://primer.style/octicons/code-16)?

**Comment by Mqxx** [comment]
Yea I think this looks good. What color?

**Comment by ghost** [comment]
Maybe blue like the note icon?

**Comment by ghost** [comment]
or a turquoise?

**Comment by Mqxx** [comment]
I try the blue one

**Comment by Mqxx** [comment]
> Do you like the idea of an "example" badge?

Added!

**Comment by ghost** [comment]
Cool! I was look at the GitHub styling guide that you linked and in the [color](https://primer.style/design/components/icon#color) section, it shows the checkmark being used for "successful" or "passing"

**Comment by Mqxx** [comment]
okay

**Comment by Mqxx** [comment]
Should I rename the badge instead?

**Comment by ghost** [comment]
Yeah, probably a better idea

**Comment by Mqxx** [comment]
Changed!

**Comment by Mqxx** [comment]
Any other suggestions or can I close the issue now?

**Comment by ghost** [comment]
I think that's a good list! Thanks for doing this. It can be closed.
