### ISSUE TITLE
New positions

### ISSUE THREAD

**Issue by extencil** [Mqxx/GitHub-Markdown#7]
It would be interesting to insert different ways of positioning in the readme, as is done with the "align" attribute (left | center | right).

**Comment by Mqxx** [comment]
Should I add more position examples? I'm not sure why anyone would want to position the badges right-aligned or centered.

**Comment by extencil** [comment]
I think it could be interesting. In my profile, I made a small integration of your solution and it was cool.

Maybe it could look better by positioning the icons at different points.

**Comment by Mqxx** [comment]
Okay I think it's a cool idea. I will update the README and point out more the alignment. Thanks for your suggestion.

Problem is that the alignment does not really work. See [here](https://stackoverflow.com/questions/12090472/how-do-i-center-an-image-in-the-readme-md-file-on-github) for more info
