### ISSUE TITLE
Text variations for icons

### ISSUE THREAD

**Issue by eze-kiel** [Mqxx/GitHub-Markdown#8]
Hi, thanks for your work! This is really useful while waiting for Github to support callout blocks.

Would it be possible to add some text variations to the icons? For example, I would love to have the Success icon (<picture><source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/Mqxx/GitHub-Markdown/main/blockquotes/badge/light-theme/success.svg"><img alt="Success" src="https://raw.githubusercontent.com/Mqxx/GitHub-Markdown/main/blockquotes/badge/dark-theme/success.svg"></picture>) with other texts, such as:

* Solution
* Check
* Complete

Maybe some other texts variations can also be added for other icons, but I do not have any idea for them right now.

**Comment by Mqxx** [comment]
I can create other variations of the success label with different text. 👍😉

**Comment by Mqxx** [comment]
Added!

**Comment by eze-kiel** [comment]
Thanks a lot :heart:

**Comment by Mqxx** [comment]
No problem!
